### ISSUE TITLE
Screenshot Issues

### ISSUE THREAD

**Issue by kasideecampbell** [Media-Ed-Online/intro-web-dev-2018spr-resources#19]
![image](https://user-images.githubusercontent.com/35854882/35835416-2d807854-0aa0-11e8-8592-2fb96f3e0778.png)

I can't get my screenshot to show up in Github, but it shows up in my preview on Atom.

**Comment by kmj1989** [comment]
I also have same problem. Thus, I linked with another way like:
![image]  (https://github.com/kmj1989/web-dev-hw/blob/master/assignment-2/images/image.JPG)

I got the address in my image file of github. However, I am not sure it is right or not because I can see the image on my github but not on atom preview.
Thus, I want to ask to Evans, why atom preview and github show differently, and how can I solve it.

**Comment by kasideecampbell** [comment]
Thanks for the tip!

**Comment by JustineEvansUM** [comment]
Hey, @kasideecampbell;

To get a relative link to work with both your Atom and GitHub.com submission, you need to make sure that your link matches your file and folder names _exactly,_ including all capital letters. So by looking at your screenshot and GH account, your link would be `![Image of Assignment 2](./Images/Screenshot2.png)` Notice how I had to capitalize 'Screenshot2.png,' since your file name was capitalized also, but it wasn't in your original screenshot above.

It continues not to work with your absolute URL because you forgot to add the file at the end. :) https://github.com/kasideecampbell/web-dev-hw/blob/master/assignment-2/images/Screenshot2.png is your full link.
