### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by Jorpatterson** [Media-Ed-Online/intro-web-dev-2018spr-resources#31]
How do I know how big my image is? And is there a particular reason it should be 300px or smaller?

**Comment by DMecam** [comment]
You can check the size of the image at Properties>Details
![answer-1](https://user-images.githubusercontent.com/31718277/36192726-247d6f4a-1163-11e8-9fe4-9ba583b9be50.jpg)
Also, if you need to search them you can filter the images by size using google images' toolbar.
![answer-2](https://user-images.githubusercontent.com/31718277/36192788-6bb173fc-1163-11e8-8654-c0147e91dac8.jpg)
I think that it should be that size because it would be easier to display it on the website without problem, but I'm not sure.
(Sorry, all the text on the screenshots is Spanish)

**Comment by Jorpatterson** [comment]
Thank you! @DMecam
